#!/usr/bin/env sh

# Enable scripting-addition automatically on Big Sur
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action ="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
#yabai -m config focus_follows_mouse          autoraise
yabai -m config focus_follows_mouse 	     off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                   4 
yabai -m config bottom_padding                4 
yabai -m config left_padding                  4 
yabai -m config right_padding                 4 
yabai -m config window_gap                    2 

# window rules
yabai -m rule --add app="^Franz$" space=5
yabai -m rule --add app="^Spotify$" space=3
yabai -m rule --add app="^Discord$" space=4
yabai -m rule --add app="^System Preferences$" manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
